.TH NUCLEO-CONFIG 1 "December 3, 2008"
.SH NAME
nucleo-config \- show configuration of the nucleo toolkit

.SH SYNOPSIS
.B nucleo-config

.SH DESCRIPTION
\fBnucleo-config\fP show the configuration of the nucleo toolkit.
For more information, please see the homepage of nucleo :
<http://insitu.lri.fr/~roussel/projects/nucleo/>

.SH AUTHOR
nucleo-config was written by Nicolas Roussel <roussel@lri.fr>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
