.TH VIDEO-SERVER 1 "December 3, 2008"
.SH NAME
videoServer \- a video application using nucleo toolkit

.SH SYNOPSIS
.B videoServer

.SH OPTIONS
.TP
\fB\-h\fP
Show the help.

.SH DESCRIPTION
\fBvideoServer\fP is a video application using nucleo toolkit.
For more information, please see the \-h option and the homepage of nucleo :
<http://insitu.lri.fr/~roussel/projects/nucleo/>

.SH AUTHOR
videoServer was written by Nicolas Roussel <roussel@lri.fr>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
