.TH VIDEO-CLIENT 1 "December 3, 2008"
.SH NAME
videoClient \- a client for videoServer application

.SH SYNOPSIS
.B videoClient

.SH OPTIONS
.TP
\fB\-h\fP
Show the help.

.SH DESCRIPTION
\fBvideoClient\fP is an application using videoServer from the nucleo package.
For more information, please see the \-h option and the homepage of nucleo :
<http://insitu.lri.fr/~roussel/projects/nucleo/>

.SH AUTHOR
videoClient was written by Nicolas Roussel <roussel@lri.fr>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
